version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server --requirepass $REDIS_PASS
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
